[versions]
flywheel = "1.0.6"
mixinextras = "0.5.0"
ponder = "1.0.82+mc1.21.1"

[libraries]
aeronautics = "maven.modrinth:create-aeronautics:1.3.2+mc1.21.1"
cdg = "maven.modrinth:create-diesel-generators:1.21.1-1.3.7"
cca = "maven.modrinth:createaddition:neoforge-1.21.1-1.5.8"
create = "com.simibubi.create:create-1.21.1:6.0.10-280"
copycats = "maven.modrinth:copycats:3.0.4+mc.1.21.1-neoforge"
create-kinetic = "maven.modrinth:create-kinetic:1.2.7.1"
creative-mode-tweaks = "maven.modrinth:creative-mode-tweaks:2.2.6"
flywheel-neoforge-api = { module = "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
flywheel-neoforge = { module = "dev.engine-room.flywheel:flywheel-neoforge-1.21.1", version.ref = "flywheel" }
geckolib-neoforge = "software.bernie.geckolib:geckolib-neoforge-1.21.1:4.7.2"
iris = "maven.modrinth:iris:1.8.14-beta.1+1.21.1-neoforge"
jei-neoforge = "mezz.jei:jei-1.21.1-neoforge:19.25.0.322"
kubejs = "dev.latvian.mods:kubejs-neoforge:2101.7.2-build.285"
kubejs-create = "maven.modrinth:kubejs-create:2101.3.1-build.18"
mixin = "org.spongepowered:mixin:0.8.7"
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras-neoforge = { module = "io.github.llamalad7:mixinextras-neoforge", version.ref = "mixinextras" }
ponder-neoforge = { module = "net.createmod.ponder:ponder-neoforge", version.ref = "ponder" }
registrate = "com.tterrag.registrate:Registrate:MC1.21-1.3.0+67"
rhino = "dev.latvian.mods:rhino:2101.2.7-build.81"
sable = "dev.ryanhcode.sable:sable-neoforge-1.21.1:2.0.3"
sable-companion = "dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:1.6.0"
tfmg = "maven.modrinth:create-tfmg:1.1.0e"
tfmg-ce = "maven.modrinth:tfmg-community-edition:1.3.0"
